### ISSUE TITLE
Autolayout issue.

### ISSUE THREAD

**Issue by datomnurdin** [oauth-io/ios-swift-example#2]
Your Main.Storyboard looks weird. I can't find button twitter in View Controller. I just saw button 2,3 and label.

![screen shot 2015-05-15 at 12 21 04 am](https://cloud.githubusercontent.com/assets/5416242/7636151/db00bd48-fa97-11e4-891a-dcc2fdcdcb0c.png)

Please advice. Thank you.

**Comment by bumpmann** [comment]
I fixed it for xcode 8 when i updated it to swift 3
